- name: Upgrade RouterOS version
  gather_facts: no
  hosts: all
  tasks:
    - name: check for available updates
      routeros_command:
        commands: "/system package update check-for-updates"
      register: output

    - name: Upgrade packages
      routeros_command:
        commands: "/system package update install"
      when: output.stdout is search('available')